name: ci

on:
  push:
    branch: [$default_branch]
  pull_request:
    branch: [$default_branch]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: |
        npm install
        npm run build
        grunt build-test-page


  screenshot-circuit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: |
        npm install
        npm run build
        node PuppeteerScreenshotCircuit.js --no-sandbox
    - uses: actions/upload-artifact@v4
      with:
        name: screenshot
        path: screenshot.png
