name: Publish to GitHub Pages

on:
  push:
    branches: [$default-branch]
    paths-ignore:
      - '.devcontainer/**'
      - '.vscode/**'
      # - 'out/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      with:
        node-version: 18.x
      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          single-commit: true
